/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{vue,js}', './projects/**/*.{vue,js}'],
  corePlugins: {
    preflight: false,
  },
  theme: {
    extend: {
      colors: {
        'surface-container-lowest': '#ffffff',
        'surface-variant': '#e4e2e4',
        'on-tertiary-fixed-variant': '#45474b',
        'on-error-container': '#93000a',
        tertiary: '#5a5c60',
        'surface-container-low': '#f6f3f5',
        'on-tertiary-container': '#fdfcff',
        'error-container': '#ffdad6',
        'tertiary-fixed-dim': '#c6c6cb',
        'surface-dim': '#dcd9dc',
        surface: '#fcf8fb',
        'primary-fixed': '#d8e2ff',
        'surface-container-high': '#eae7ea',
        background: '#fcf8fb',
        'on-background': '#1b1b1d',
        'on-primary-container': '#fefcff',
        'inverse-surface': '#303032',
        'primary-container': '#0070eb',
        'inverse-primary': '#adc6ff',
        'inverse-on-surface': '#f3f0f2',
        'tertiary-container': '#737479',
        'outline-variant': '#c1c6d7',
        'surface-container': '#f0edef',
        'on-primary-fixed': '#001a41',
        'on-primary': '#ffffff',
        error: '#ba1a1a',
        'on-tertiary-fixed': '#1a1c1f',
        secondary: '#5d5e63',
        'surface-bright': '#fcf8fb',
        'on-tertiary': '#ffffff',
        'tertiary-fixed': '#e2e2e7',
        'surface-container-highest': '#e4e2e4',
        'on-secondary-fixed-variant': '#46464b',
        'on-primary-fixed-variant': '#004493',
        'secondary-container': '#e0dfe4',
        primary: '#0058bc',
        'primary-fixed-dim': '#adc6ff',
        outline: '#717786',
        'on-secondary': '#ffffff',
        'surface-tint': '#005bc1',
        'on-secondary-container': '#626267',
        'secondary-fixed': '#e3e2e7',
        'on-secondary-fixed': '#1a1b1f',
        'on-error': '#ffffff',
        'on-surface-variant': '#414755',
        'secondary-fixed-dim': '#c6c6cb',
        'on-surface': '#1b1b1d',
        theme: {
          primary: 'rgb(var(--app-color-primary-rgb) / <alpha-value>)',
          hover: 'var(--app-color-primary-hover)',
          active: 'var(--app-color-primary-active)',
        },
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        xxl: '48px',
        xxxl: '64px',
        unit: '4px',
        'container-max': '1200px',
        gutter: '20px',
        'margin-desktop': '40px',
        'margin-mobile': '16px',
      },
      fontFamily: {
        'headline-lg-mobile': ['Inter', 'PingFang SC', 'Microsoft YaHei'],
        'label-sm': ['Inter', 'PingFang SC', 'Microsoft YaHei'],
        'headline-md': ['Inter', 'PingFang SC', 'Microsoft YaHei'],
        display: ['Inter', 'PingFang SC', 'Microsoft YaHei'],
        'headline-lg': ['Inter', 'PingFang SC', 'Microsoft YaHei'],
        'body-sm': ['Inter', 'PingFang SC', 'Microsoft YaHei'],
        'label-md': ['Inter', 'PingFang SC', 'Microsoft YaHei'],
        title: ['Inter', 'PingFang SC', 'Microsoft YaHei'],
        'body-lg': ['Inter', 'PingFang SC', 'Microsoft YaHei'],
      },
      fontSize: {
        'headline-lg-mobile': ['28px', { lineHeight: '34px', letterSpacing: '-0.022em', fontWeight: '700' }],
        'label-sm': ['11px', { lineHeight: '13px', letterSpacing: '0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '30px', letterSpacing: '-0.019em', fontWeight: '600' }],
        display: ['48px', { lineHeight: '56px', letterSpacing: '-0.022em', fontWeight: '700' }],
        'headline-lg': ['34px', { lineHeight: '41px', letterSpacing: '-0.022em', fontWeight: '700' }],
        'body-sm': ['15px', { lineHeight: '20px', letterSpacing: '-0.012em', fontWeight: '400' }],
        'label-md': ['13px', { lineHeight: '18px', letterSpacing: '-0.01em', fontWeight: '500' }],
        title: ['20px', { lineHeight: '25px', letterSpacing: '-0.017em', fontWeight: '600' }],
        'body-lg': ['17px', { lineHeight: '22px', letterSpacing: '-0.015em', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
